"""Constants for PSA Car Controller integration."""
from datetime import timedelta

DOMAIN = "psacc"
CONF_API_URL = "api_url"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_VIN = "vin"

DEFAULT_UPDATE_INTERVAL = 5  # minutes
MIN_UPDATE_INTERVAL = 1
MAX_UPDATE_INTERVAL = 60

# API Endpoints
API_VEHICLES = "/vehicles"
API_STATUS = "/get_vehicleinfo/{vin}"
API_CHARGE_NOW = "/charge_now/{vin}/{charge}"
API_CHARGE_HOUR = "/charge_control"
API_CLIMATE_START = "/climate/{vin}/{temperature}"
API_CLIMATE_STOP = "/climate/{vin}/0"
API_WAKEUP = "/wakeup/{vin}"
API_HORN = "/horn/{vin}/{count}"
API_LIGHTS = "/lights/{vin}/{count}"
API_LOCK = "/door_lock/{vin}"
API_UNLOCK = "/door_unlock/{vin}"
API_PRECONDITIONING = "/preconditioning/{vin}/{temp}"
API_CHARGE_THRESHOLD = "/charge_control"

# Entity attributes
ATTR_VIN = "vin"
ATTR_BRAND = "brand"
ATTR_MODEL = "model"
ATTR_BATTERY_LEVEL = "battery_level"
ATTR_BATTERY_CAPACITY = "battery_capacity"
ATTR_RANGE_ELECTRIC = "range_electric"
ATTR_RANGE_FUEL = "range_fuel"
ATTR_TOTAL_RANGE = "total_range"
ATTR_CHARGING = "charging"
ATTR_PLUGGED = "plugged"
ATTR_CHARGING_POWER = "charging_power"
ATTR_CHARGING_RATE = "charging_rate"
ATTR_CHARGING_TIME = "charging_remaining_time"
ATTR_POSITION = "position"
ATTR_LATITUDE = "latitude"
ATTR_LONGITUDE = "longitude"
ATTR_ALTITUDE = "altitude"
ATTR_MILEAGE = "mileage"
ATTR_DOORS_LOCKED = "doors_locked"
ATTR_DOOR_DRIVER = "door_driver"
ATTR_DOOR_PASSENGER = "door_passenger"
ATTR_DOOR_REAR_LEFT = "door_rear_left"
ATTR_DOOR_REAR_RIGHT = "door_rear_right"
ATTR_HOOD = "hood"
ATTR_TRUNK = "trunk"
ATTR_WINDOWS = "windows"
ATTR_CLIMATE_ACTIVE = "climate_active"
ATTR_TEMPERATURE_EXT = "temperature_exterior"
ATTR_TEMPERATURE_INT = "temperature_interior"
ATTR_TEMPERATURE_TARGET = "temperature_target"
ATTR_LAST_UPDATE = "last_update"
ATTR_ENGINE_RUNNING = "engine_running"
ATTR_FUEL_LEVEL = "fuel_level"
ATTR_CONSUMPTION = "average_consumption"
ATTR_CHARGE_THRESHOLD = "charge_threshold"

# Device info
MANUFACTURER = "PSA"
MODEL = "Connected Car"

# Services
SERVICE_SET_CHARGE_THRESHOLD = "set_charge_threshold"
SERVICE_SET_CHARGE_SCHEDULE = "set_charge_schedule"
SERVICE_START_CLIMATE = "start_climate"
SERVICE_STOP_CLIMATE = "stop_climate"
SERVICE_HORN = "horn"
SERVICE_LIGHTS = "lights"
SERVICE_WAKEUP = "wakeup"
SERVICE_GET_STATISTICS = "get_statistics"

# Service parameters
ATTR_THRESHOLD = "threshold"
ATTR_START_TIME = "start_time"
ATTR_END_TIME = "end_time"
ATTR_TEMPERATURE = "temperature"
ATTR_COUNT = "count"
ATTR_PERIOD = "period"

# Icon mappings
ICON_BATTERY = "mdi:battery"
ICON_BATTERY_CHARGING = "mdi:battery-charging"
ICON_RANGE = "mdi:gauge"
ICON_CHARGING = "mdi:ev-station"
ICON_PLUGGED = "mdi:power-plug"
ICON_DOOR = "mdi:car-door"
ICON_DOOR_LOCK = "mdi:lock"
ICON_DOOR_UNLOCK = "mdi:lock-open"
ICON_CLIMATE = "mdi:air-conditioner"
ICON_TEMPERATURE = "mdi:thermometer"
ICON_LOCATION = "mdi:map-marker"
ICON_MILEAGE = "mdi:counter"
ICON_CONSUMPTION = "mdi:flash"
ICON_CAR = "mdi:car-electric"
ICON_HORN = "mdi:bugle"
ICON_LIGHTS = "mdi:car-light-high"
